# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegated_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=300, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('observations', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('applicant', models.CharField(max_length=100)),
                ('date_initial', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='State_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('date_initial', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=20)),
                ('observations', models.CharField(max_length=200, null=True)),
                ('id_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_sam.Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('discountable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='permissions',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_sam.Type_Permissions'),
        ),
        migrations.AddField(
            model_name='delegated_activities',
            name='id_permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_sam.Permissions'),
        ),
    ]
