# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_sam', '0006_auto_20180218_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceptacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_residencia', django_countries.fields.CountryField(max_length=2)),
                ('provincia_residencia', models.CharField(max_length=20)),
                ('ciudad_residencia', models.CharField(max_length=20)),
                ('parroquia_residencia', models.CharField(max_length=20)),
                ('tipo_parroquia', models.CharField(choices=[('URBANO', 'Urbano'), ('URBANO-MARGINAL', 'Urbano-marginal'), ('RURAL', 'Rural')], default='', max_length=20)),
                ('barrio', models.CharField(max_length=20)),
                ('zona', models.CharField(choices=[('NORTE', 'Norte'), ('CENTRO', 'Centro'), ('SUR', 'Sur'), ('VALLES', 'Valles'), ('SUBURBIO', 'Suburbio'), ('ZONA RURAL', 'Zona Rural')], default='', max_length=15)),
                ('direccion_principal', models.CharField(max_length=30)),
                ('direccion_secundaria', models.CharField(max_length=30)),
                ('direccion_numero', models.CharField(max_length=20)),
                ('telefono_casa', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono del Domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_id', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_nacimiento', django_countries.fields.CountryField(default='EC', max_length=2)),
                ('ciudad_nacimiento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Socioeco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('inicio', models.DateField(auto_now_add=True)),
                ('enviado', models.DateField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('motivo_solicitud', models.TextField(blank=True, default='', null=True)),
                ('capacidad_pago', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_vivienda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_alimentacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_educacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_transporte', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_salud', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_vestimenta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('gastos_otros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('evaluacion_socioeco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencias', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('negocios', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('inversiones', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('arriendos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('otros', models.CharField(blank=True, max_length=120)),
                ('otros_ingreso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('evaluacion_socioeco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante_Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_id', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTERO', 'Soltero'), ('VIUDO', 'Viudo'), ('DIVORCIADO', 'Divorciado'), ('OTRO', 'Otro')], default='', max_length=10)),
                ('parentesco', models.CharField(max_length=20)),
                ('nivel_estudios', models.CharField(choices=[('BASICA', 'B\xe1sica'), ('BACHILLERATO', 'Bachillerato'), ('TERCER NIVEL', 'Tercer Nivel'), ('CUARTO NIVEL', 'Cuarto Nivel')], default='', max_length=15)),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('enfermedad_cronica', models.CharField(blank=True, max_length=50)),
                ('discapacidad', models.CharField(blank=True, max_length=50)),
                ('validado', models.BooleanField(default=False)),
                ('evaluacion_socioeco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inmuebles', models.IntegerField()),
                ('valor_inmuebles', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_vehiculos', models.IntegerField()),
                ('valor_vehiculos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evaluacion_socioeco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('TIO', 'T\xedo'), ('TIA', 'T\xeda'), ('OTRO', 'Otro')], max_length=6)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_id', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTERO', 'Soltero'), ('VIUDO', 'Viudo'), ('DIVORCIADO', 'Divorciado'), ('OTRO', 'Otro')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_nacimiento', django_countries.fields.CountryField(default='EC', max_length=2)),
                ('ciudad_nacimiento', models.CharField(max_length=20)),
                ('nivel_estudios', models.CharField(choices=[('BASICA', 'B\xe1sica'), ('BACHILLERATO', 'Bachillerato'), ('TERCER NIVEL', 'Tercer Nivel'), ('CUARTO NIVEL', 'Cuarto Nivel')], max_length=15)),
                ('titulo', models.CharField(blank=True, max_length=30)),
                ('telefono_casa', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono del Domicilio')),
                ('telefono_celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese su celular en el formato 0990909090.', regex='^0+\\d{9}$')], verbose_name='Tel\xe9fono Celular')),
                ('operadora_celular', models.CharField(choices=[('MOVISTAR', 'Movistar'), ('CLARO', 'Claro'), ('CNT', 'Cnt')], max_length=8)),
                ('numero_hijos', models.IntegerField()),
                ('lugar_trabajo', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('tiempo_trabajo', models.IntegerField()),
                ('direccion_trabajo', models.CharField(max_length=250)),
                ('telefono_trabajo', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono del Trabajo')),
                ('correo_personal', models.EmailField(max_length=254)),
                ('correo_trabajo', models.EmailField(max_length=254)),
                ('evaluacion_socioeco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_gastos', models.CharField(max_length=100)),
                ('evaluacion_socioeco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.CreateModel(
            name='Situacion_Habitacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posesion_vivienda', models.CharField(choices=[('PROPIA', 'Propia'), ('ARRENDADA', 'Arrendada'), ('CEDIDA POR EL TRABAJO', 'Cedida por el trabajo'), ('CEDIDA POR ALGUN FAMILIAR', 'Cedida por alg\xfan familiar'), ('OTRA', 'otra')], default='', max_length=20)),
                ('tipo_vivienda', models.CharField(max_length=40)),
                ('estructura_vivienda', models.CharField(choices=[('CONCRETO', 'Concreto'), ('ADOBE', 'Adobe'), ('MADERA', 'Madera')], default='', max_length=10)),
                ('agua_potable', models.BooleanField()),
                ('alcantarillado', models.BooleanField()),
                ('electricidad', models.BooleanField()),
                ('telefono_fijo', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('tv_cable', models.BooleanField()),
                ('evaluacion_socioeco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion_socioeco',
            unique_together=set([('email', 'resuelto')]),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='evaluacion_socioeco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Clase'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='evaluacion_socioeco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco'),
        ),
        migrations.AddField(
            model_name='aceptacion',
            name='evaluacion_socioeco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socioeco_sam.Evaluacion_Socioeco'),
        ),
        migrations.AlterUniqueTogether(
            name='representante',
            unique_together=set([('evaluacion_socioeco', 'nombres', 'apellido_paterno', 'apellido_materno', 'numero_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='integrante_familia',
            unique_together=set([('evaluacion_socioeco', 'nombres_completos', 'numero_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together=set([('evaluacion_socioeco', 'nombres', 'apellido_paterno', 'apellido_materno', 'numero_id')]),
        ),
    ]
