# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioeco_sam', '0003_evaluacion_socioeco_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_socioeco',
            name='familia',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
