# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioeco_sam', '0005_auto_20180517_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='gastos_alimentacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_educacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_otros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_salud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_transporte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_vestimenta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gastos_vivienda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='arriendos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='dependencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='inversiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='negocios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='otros_ingreso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='valor_inmuebles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='valor_vehiculos',
            field=models.IntegerField(default=0),
        ),
    ]
