# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioeco_sam', '0006_auto_20180521_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante_familia',
            name='nivel_estudios',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('BASICA', 'B\xe1sica'), ('BACHILLERATO', 'Bachillerato'), ('TERCER NIVEL', 'Tercer Nivel'), ('CUARTO NIVEL', 'Cuarto Nivel')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='representante',
            name='operadora_celular',
            field=models.CharField(choices=[('MOVISTAR', 'Movistar'), ('CLARO', 'Claro'), ('CNT', 'Cnt'), ('OTRA', 'Otra')], max_length=8),
        ),
    ]
