# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('boo_id', models.AutoField(primary_key=True, serialize=False)),
                ('boo_title', models.CharField(max_length=80)),
                ('boo_author', models.CharField(max_length=50)),
                ('boo_edition', models.CharField(blank=True, max_length=30)),
                ('boo_language', models.CharField(max_length=15)),
                ('boo_subject', models.CharField(blank=True, max_length=50)),
                ('boo_publishinghouse', models.CharField(blank=True, max_length=20)),
                ('boo_publication', models.DateField(blank=True, null=True)),
                ('boo_acquisition', models.DateField(blank=True, null=True)),
                ('boo_observation', models.CharField(blank=True, max_length=80)),
                ('boo_value', models.IntegerField(blank=True)),
                ('boo_state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('bor_id', models.AutoField(primary_key=True, serialize=False)),
                ('bor_datebor', models.DateField(blank=True, null=True)),
                ('bor_datereturn', models.DateField(blank=True, null=True)),
                ('bor_datemax', models.DateField(blank=True, null=True)),
                ('bor_observation', models.CharField(blank=True, max_length=80)),
                ('boo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_sam.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('rea_id', models.AutoField(primary_key=True, serialize=False)),
                ('rea_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='rea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_sam.Reader'),
        ),
    ]
