# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones_sam', '0003_direccion_envio_direccion_envio_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='attachment_mimetype',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
