# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 17:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('identity_card', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex=b'^0+\\d{8}$')], verbose_name='Tel\xe9fono de Domicilio')),
                ('cell', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese su celular en el formato 0990909090.', regex=b'^0+\\d{9}$')], verbose_name='Tel\xe9fono Celular')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
