# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_sam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='id_students',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
