# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_sam', '0002_auto_20171003_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_s', models.CharField(max_length=254)),
                ('email_r', models.CharField(max_length=254)),
            ],
        ),
    ]
