# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_sam', '0003_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='id',
        ),
        migrations.AlterField(
            model_name='relation',
            name='identity',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
