# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex=b'^0+\\d{8}$')], verbose_name='Tel\xe9fono de Domicilio del Representante')),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese su celular en el formato 0990909090.', regex=b'^0+\\d{9}$')], verbose_name='Tel\xe9fono Celular del Representante')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Det_Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=80)),
                ('talla', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes_sam.Cab_Proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes_Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[(b'P', b'Padre'), (b'M', b'Madre'), (b'T', b'T\xc3\xado / t\xc3\xada'), (b'A', b'Abuelo / abuela'), (b'O', b'Otro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uniformes',
            fields=[
                ('id_uniformes', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=80)),
                ('talla', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='estudiantes_representante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes_sam.Lista_Estudiantes'),
        ),
        migrations.AddField(
            model_name='estudiantes_representante',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes_sam.Lista_Representante'),
        ),
        migrations.AddField(
            model_name='det_proforma',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes_sam.Lista_Estudiantes'),
        ),
        migrations.AddField(
            model_name='cab_proforma',
            name='id_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes_sam.Lista_Representante'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantes_representante',
            unique_together=set([('estudiante', 'representante', 'relacion')]),
        ),
    ]
