# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capellan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ControlDeFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InformeGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fortalezas_actitud', models.TextField(blank=True)),
                ('fortalezas_destrezas', models.TextField(blank=True)),
                ('debilidades_actitud', models.TextField(blank=True)),
                ('debilidades_destrezas', models.TextField(blank=True)),
                ('estrategias', models.TextField(blank=True)),
                ('reunion_padres', models.BooleanField(default=False)),
                ('fecha_reunion', models.DateField(blank=True)),
                ('acuerdos_padres', models.TextField(blank=True)),
                ('reunion_estudiante', models.BooleanField()),
                ('acuerdos_estudiante', models.TextField(blank=True)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('pedidos_apoyo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformeNovedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('novedades', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformeRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comportamientos', models.TextField(blank=True)),
                ('estrategias', models.TextField(blank=True)),
                ('reunion_padres', models.BooleanField(default=False)),
                ('fecha_reunion', models.DateField(blank=True)),
                ('acuerdos_padres', models.TextField(blank=True)),
                ('reunion_estudiante', models.BooleanField()),
                ('acuerdos_estudiante', models.TextField(blank=True)),
                ('fortalezas_estudiante', models.TextField(blank=True)),
                ('fecha_psicologia', models.DateField(blank=True)),
                ('fecha_capelllania', models.DateField(blank=True)),
                ('acuerdos', models.TextField(blank=True)),
                ('constancia_psicologia', models.DateField(blank=True)),
                ('constancia_capellania', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformeSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('aspectos_estudiante', models.TextField(blank=True)),
                ('academicos_antes', models.TextField(blank=True)),
                ('academicos_ahora', models.TextField(blank=True)),
                ('actitud_antes', models.TextField(blank=True)),
                ('actitud_ahora', models.TextField(blank=True)),
                ('estrategias', models.TextField(blank=True)),
                ('reunion_padres', models.BooleanField(default=False)),
                ('fecha_reunion', models.DateField(blank=True)),
                ('acuerdos_padres', models.TextField(blank=True)),
                ('reunion_estudiante', models.BooleanField()),
                ('acuerdos_estudiante', models.TextField(blank=True)),
                ('informacion_adicional', models.TextField(blank=True)),
                ('pedidos_apoyo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
