# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('admisiones_sam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('identity', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese solo numeros y letras.', regex='^[a-zA-Z0-9_]+$')], verbose_name='N\xfamero de Identificaci\xf3n')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('father_last_name', models.CharField(max_length=30, verbose_name='father last name')),
                ('mother_last_name', models.CharField(max_length=30, verbose_name='mother last name')),
                ('birthdate', models.DateField(null=True, verbose_name='birth date')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono del Domicilio')),
                ('cell', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese su celular en el formato 0990909090.', regex='^0+\\d{9}$')], verbose_name='Tel\xe9fono Celular')),
                ('address', models.CharField(max_length=80)),
                ('birth_country', django_countries.fields.CountryField(max_length=2)),
                ('country_home', django_countries.fields.CountryField(max_length=2)),
                ('user_photo', models.ImageField(upload_to='static/user/profile_photo/')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='LoginRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dead', models.BooleanField(default=False)),
                ('instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('address_work', models.CharField(blank=True, max_length=80, null=True)),
                ('office', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono de Oficina')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='email address')),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_student', models.BooleanField()),
                ('withdraw', models.BooleanField()),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.People')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_grade', models.CharField(max_length=50)),
                ('medical_information', models.CharField(max_length=80)),
                ('id_applications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admisiones_sam.Applications')),
                ('id_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Padre', to=settings.AUTH_USER_MODEL)),
                ('id_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Madre', to=settings.AUTH_USER_MODEL)),
                ('id_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to=settings.AUTH_USER_MODEL)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temporal_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_s', models.EmailField(max_length=254, verbose_name='email address')),
                ('identificacion_s', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres_s', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno_s', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno_s', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion_s', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_s', models.DateTimeField(blank=True, null=True)),
                ('genero_s', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_s', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_s', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_s', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_nacimiento_s', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_recidencia_s', models.CharField(blank=True, max_length=50, null=True)),
                ('email_t', models.EmailField(max_length=254, verbose_name='email address')),
                ('identificacion_t', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres_t', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno_t', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno_t', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion_t', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_t', models.DateTimeField(blank=True, null=True)),
                ('genero_t', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_t', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_t', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_t', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_nacimiento_t', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_recidencia_t', models.CharField(blank=True, max_length=50, null=True)),
                ('email_p', models.EmailField(max_length=254, verbose_name='email address')),
                ('identificacion_p', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres_p', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno_p', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno_p', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion_p', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_p', models.DateTimeField(blank=True, null=True)),
                ('genero_p', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_p', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_p', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_p', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_nacimiento_p', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_recidencia_p', models.CharField(blank=True, max_length=50, null=True)),
                ('email_m', models.EmailField(max_length=254, verbose_name='email address')),
                ('identificacion_m', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres_m', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno_m', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno_m', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion_m', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento_m', models.DateTimeField(blank=True, null=True)),
                ('genero_m', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_m', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_m', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_m', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_nacimiento_m', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_recidencia_m', models.CharField(blank=True, max_length=50, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('migrado', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coordinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='relationshipstudent',
            name='id_students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Students'),
        ),
    ]
