# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_sam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.ImageField(default='static/user/default.jpg', upload_to='static/user/profile_photo/'),
        ),
    ]
