# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 18:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_sam', '0003_auto_20180115_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('through', models.CharField(blank=True, max_length=50, verbose_name='joined thourgh')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20)),
                ('legal_representative', models.BooleanField(default=False)),
                ('live_together', models.BooleanField(default=False)),
                ('withdraw', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=False)),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Relative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Student')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cell',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Ingrese su celular en el formato 0990909090.', regex='^0+\\d{9}$')], verbose_name='Tel\xe9fono Celular'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese su tel\xe9fono en el formato 022345678.', regex='^0+\\d{8}$')], verbose_name='Tel\xe9fono del Domicilio'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='student_relative',
            unique_together=set([('student', 'relative')]),
        ),
    ]
