# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_sam', '0001_initial'),
        ('general_sam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Students'),
        ),
        migrations.AddField(
            model_name='homeroom_registry',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Clase'),
        ),
        migrations.AddField(
            model_name='homeroom_registry',
            name='homeroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Teacher'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='periodo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Periodo_Lectivo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Nivel'),
        ),
        migrations.AddField(
            model_name='clase',
            name='periodo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Periodo_Lectivo'),
        ),
        migrations.AddField(
            model_name='aptitud_matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Students'),
        ),
        migrations.AddField(
            model_name='aptitud_matricula',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Nivel'),
        ),
        migrations.AddField(
            model_name='aptitud_matricula',
            name='periodo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Periodo_Lectivo'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula_grupo',
            unique_together=set([('matricula', 'grupo', 'inicio', 'fin')]),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('clase', 'estudiante')]),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set([('nombre', 'periodo_lectivo')]),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set([('periodo_lectivo', 'nivel', 'paralelo')]),
        ),
        migrations.AlterUniqueTogether(
            name='aptitud_matricula',
            unique_together=set([('periodo_lectivo', 'estudiante', 'nivel')]),
        ),
    ]
