# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_sam', '0002_auto_20180114_2242'),
        ('general_sam', '0002_auto_20170926_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Profesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Escolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('area_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_sam.Seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Materia_Escolar')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion_profesores',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Materia_Grupo'),
        ),
        migrations.AddField(
            model_name='asignacion_profesores',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_sam.Teacher'),
        ),
    ]
