# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_sam', '0003_auto_20180114_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_escolar',
            name='area_academica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_sam.Area_Academica'),
        ),
    ]
