# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_sam', '0005_seccion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_academica',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
