# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_sam', '0006_auto_20180218_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_activa', models.BooleanField()),
                ('observaciones', models.CharField(blank=True, max_length=400)),
                ('inicio', models.DateField(auto_now_add=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_sam.Matricula')),
            ],
        ),
    ]
