# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_sam', '0009_auto_20180716_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitud_matricula',
            name='resuelto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aptitud_matricula',
            name='tipo',
            field=models.CharField(choices=[('A', 'Antiguo'), ('N', 'Nuevo')], max_length=1),
        ),
    ]
