# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones_sam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applied_grade',
            field=models.CharField(choices=[('Inicial 1 (de 2 a 3 a\xf1os)', 'Inicial 1 (de 2 a 3 a\xf1os)'), ('Inicial 2 (de 3 a 4 a\xf1os)', 'Inicial 2 (de 3 a 4 a\xf1os)'), ('Inicial 2 (de 4 a 5 a\xf1os) / Prekinder', 'Inicial 2 (de 4 a 5 a\xf1os) / Prekinder'), ('1ro de B\xe1sica / Kinder', '1ro de B\xe1sica / Kinder'), ('2do de B\xe1sica / 1st Grade', '2do de B\xe1sica / 1st Grade'), ('3ro de B\xe1sica / 2nd Grade', '3ro de B\xe1sica / 2nd Grade'), ('4to de B\xe1sica / 3rd Grade', '4to de B\xe1sica / 3rd Grade'), ('5to de B\xe1sica / 4th Grade', '5to de B\xe1sica / 4th Grade'), ('6to de B\xe1sica / 5th Grade', '6to de B\xe1sica / 5th Grade'), ('7mo de B\xe1sica / 6th Grade', '7mo de B\xe1sica / 6th Grade'), ('8vo de B\xe1sica / 7th Grade', '8vo de B\xe1sica / 7th Grade'), ('9no de B\xe1sica / 8th Grade', '9no de B\xe1sica / 8th Grade'), ('10mo de B\xe1sica / 9th Grade', '10mo de B\xe1sica / 9th Grade'), ('1ro de Bachillerato / 10th Grade', '1ro de Bachillerato / 10th Grade'), ('2do de Bachillerato / 11th Grade', '2do de Bachillerato / 11th Grade'), ('3ro de Bachillerato / 12th Grade', '3ro de Bachillerato / 12th Grade')], max_length=50, verbose_name='Nivel al que aplica'),
        ),
    ]
