# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 14:41
from __future__ import unicode_literals

import admisiones_sam.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones_sam', '0002_auto_20180114_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDepartmentTest',
            fields=[
                ('id_accountingtest', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('observations', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='bank_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='special_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='mail',
            field=models.EmailField(default='reemplazar@montebelloacademy.org', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_tests',
            name='date_test_pre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type_tests',
            name='time_test_pre',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='det_documents',
            name='file',
            field=models.FileField(upload_to=b'admisiones_sam/documents/', validators=[admisiones_sam.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='det_reports',
            name='materia',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='det_reports',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='det_reports',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reports_tests',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingdepartmenttest',
            name='id_applications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones_sam.Applications'),
        ),
    ]
