# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 16:37
from __future__ import unicode_literals

import admisiones_sam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones_sam', '0003_auto_20180514_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_documents',
            name='file',
            field=models.FileField(upload_to=b'admisiones_sam/', validators=[admisiones_sam.models.validate_file_extension]),
        ),
    ]
