# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones_sam', '0004_auto_20180514_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_tests',
            name='time_test_pre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
